// Java is platform independent
/*intermediate bytecode is generated by compiler which can be run on any
machine, whereas in c++, compiler generates an executable which is different
for different machines. That is why java is portable programming language*/
// -----------------------------------------------------------------
/* Java is popular 
Java is simple (No pointers , no operator overloading or index out of bound
exception)
Java is secure(because of JVM and only references being passed)
Java has automatic garbage collector
Java is statically typed and fast
*/ 
// ------------------------------------------------ 
// to run java code, we install JDK- java development kit which has JRE - java runtime environment
// https://www.oracle.com/in/java/technologies/downloads/#jdk25-windows 
// installer and check on cmd by java -version
// Extension Pack for Java (by Microsoft) extension in vsc

// JRE= JVM + libraries (std lib to run java code)
// JDK=JRE+Dev tools like (javac, java document generator etc)

// JVM converts bytecode to machine code
// ----------------------------------------------
// Every code must be a part of some class
// class name= program name
// static means a method which can be used without creating an object
// --------------------------------------------------------------
public class Intro{
    public static void main(String args[]){System.out.println("hi");
// System is a standard java class
// out is the object of printstream class
// println is a method to print

}}

// ----------------------------
// compilation: source code (.java): compiler takes the source code and converts to byte code(.class)
// execution: byte code taken by JVM and is converted to machine native code.
// -----------------------------
// to run the file in vsc:
// click on run near psvm
// or javac programName.java then java ProgramName
